# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
    
      envLevel:
        description: 'Environment'
        required: true
        default: dev
        type: choice
        options:
#        - prod
        - dev
        - stage

jobs:
  echo:
    runs-on: inputs.envLevel
    steps:
    - name: Run a one-line script
#      if : inputs.envLevel == 'dev' 
      run: echo Hello, dev!
