# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
    
      envLevel:
        description: 'Environment'
        required: true
        default: dev
        type: choice
        options:
#        - prod
        - dev
        - stage

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    
      dev:
        if : inputs.envLevel == 'dev' 
        uses: ./.github/workflows/dev.yml
#        run: echo Hello, dev!

      stage:
        if : inputs.envLevel == 'stage' 
        uses: ./.github/workflows/stage.yml
#run: echo Hello, stage!
